<a href="https://colab.research.google.com/github/kef135lib/advPy4lib/blob/main/KFloyd_Week_4_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 4 Homework

(Be sure to copy to drive)

I have put a lot different things in front of you during this course. Thanks for indulging me as I try to both impress you with what Python can do, and make the code readable.

For homework this week, we are going to go real light.


**H1** To bring what you learned in the week 4 warmup to life I'd like you to:

- Create a GitHub repository
- Save your week 1 homework in that GitHub Repository in the way described in the warmup
- Share the URL to your repository in the cell below

In [1]:
repository_url = "https://github.com/kef135lib/advPy4lib/blob/main/KFloyd_Week_4_Workalong.ipynb"


**H1 Continued**

You don't have to keep that repository forever, feel free to delete it after this class is done.

**H2** Starting in the week 3 homework we began an analysis on a collection of PDF files that you created. The week 4 workalong asked you to create PDF summaries for those same files.

I'd just like to see what your final analysis looks like. Run the cells below to load up those csv files and to display them to the screen.

In [2]:
from google.colab import drive
import pandas as pd

#Because the summaries are big, I'm going to set no maximum column size in pandas so I see
#the complete summary
pd.set_option('display.max_colwidth', None)

drive.mount('/content/gdrive')

Mounted at /content/gdrive

# PDF Summaries

In [3]:
pdf_summaries = pd.read_csv("/content/gdrive/MyDrive/LibraryJuicePython/adv_week4_pdf_summaries.csv")
pdf_summaries

,Filename,Summary
0,The obligation to restrict AI in student writing.pdf,"The use of generative AI in higher education has been characterized byambiguity. No set of policies has yet become the accepted norm. Even if using AI for writing is not technically plagiarism, it is a violation of the spirit of rules against plagiarism. Educators have a moral obligation to treat AI-generated text the same way they would treat text written by a person."
1,Generative AI in higher education.pdf,"The advancements in Generative Artiﬁcial Intelligence (GenAI) can provide opportunities for enriching educational experiences, but at the same time raise concerns regarding academic integrity. Many educators expressed anxiety and hesitation when it comes to integrating GenAI in their teaching practices. This study explores diﬀerent U.S. universities’ academic policies and guidelines."
2,The impact of generative AI on higher education learning and teaching.pdf,"The impact of generative AI on higher education learning and teaching. A study conducted by researchers at a leading university in Australia surveyed 30 of their teaching staff. Data were analyzed using the procedures of Inductive Thematic Analysis. Results indicate concerns exist around concepts relating to academic integrity, but these concerns may be exaggerated."
3,Your Brain on ChatGPT Accumulation of Cognitive Debt when Using an AI Assistant for Essay Writing Task.pdf,"We assigned participants to three groups: LLM group, Search Engine group, and Brain-only group. Figure 1 is a dynamic Direct Transfer Function (dDTF) EEG analysis of Alpha Band for groups."
4,AI-Infused Discovery Environments.pdf,"Artificial intelligence (AI) is rapidly making inroads into most facets of the library and education spheres. This paper outlines steps taken to examine Primo Research, an AI-infused discovery environment. The researchers aimed to evaluate the quality and relevance of the AI results in comparison to sources retrieved from the conventional search functionality."
5,Higher Education AI Policies A Document Analysis of University Guidelines.pdf,"Artificial Intelligence (AI) has been highlighted as a potentially disruptive force across several industries and in higher edu. This study investigates the content of AI policies in higher education by analysing official documents from Swedish universities. It identifies key themes and patterns, comparing them with related research and international guidelines. Expanding on the results of the study, it develops a dynamic alignment model for higher education AI policy (DAMHEAP)"
6,trajectories of AI policy in higher education.pdf,"The ethics of artificial intelligence (GenAI) in higher education has been hotly discussed, debated, and researched. The findings reveal general concerns about academic integrity, fairness, equity,privacy, and data security. Institutional ambiguity in policy supported experimentation and the appearance of progress, but risked individualising failure on teachers and students."

#PDF Details

In [4]:
pdf_data = pd.read_csv("/content/gdrive/MyDrive/LibraryJuicePython/adv_week3_homework.csv")
pdf_data

,filename,Polarity,Subjectivity,Most common term,2nd most common,3rd most common
0,Higher Education AI Policies A Document Analysis of University Guidelines.pdf.txt,0.082958,0.407519,ai,gai,swedish
1,Generative AI in higher education.pdf.txt,0.127144,0.441910,genai,n =,chatgpt
2,The impact of generative AI on higher education learning and teaching.pdf.txt,0.077890,0.477433,ai,chatgpt,artificial intelligence
3,AI-Infused Discovery Environments.pdf.txt,0.103715,0.462004,pra,ai,pve
4,trajectories of AI policy in higher education.pdf.txt,0.090184,0.444758,ai,genai,hong kong
5,The obligation to restrict AI in student writing.pdf.txt,0.088726,0.467717,ai,march,downloaded
6,Your Brain on ChatGPT Accumulation of Cognitive Debt when Using an AI Assistant for Essay Writing Task.pdf.txt,0.117622,0.473204,sessions,llm,* *


## All Done!

Congrats you have finished Advanced Python for Librarians!

Don't forget to click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work. Please also save this notebook as a PDF and upload it the Library Juice Academy LMS.